import { cookies } from 'next/headers'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { redirect } from 'next/navigation'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function ProjectLayout({
  children,
}: {
  children: React.ReactNode
}) {

    return (
        <div>
           {children}
        </div>
        
    )
}