import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Suspense } from 'react';
import NavBar from './components/NavBar';
import ReactQueryProvider from './providers/reactQuery';
import Platform from '@/components/platform';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="">
      

      <body className="flex flex-col h-screen w-screen bg-[#F3F3F3]">
      <ReactQueryProvider>
      <main className="grid grid-rows-10 grid-flow-row">
        <div className="row-span-1 sticky top-0 z-10">
          
            <NavBar />
          
        </div>

        <div className="row-span-9">
          <div className="grid grid-cols-8 grid-flow-col">
            <div className="col-span-6">
              {children}
            </div>
            <div className="col-span-2 relative">
              <div className="sticky min-h-[90vh] top-[10%] bg-[#CFE3F6]">
                <Platform />
              </div>
            </div>
          </div>
        </div>

      </main>
      </ReactQueryProvider>
      </body>
    </html>
  )
}
